sudo: required
dist: trusty
language: node_js
node_js:
- "9"
branches:
  except:
  - gh-pages
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- yarn add polymer-cli
- polymer install --variants
script:
- xvfb-run wct --skip-plugin sauce
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct --plugin sauce --skip-plugin
  local; fi
after_success:
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -k "$DEPLOYSECRET"
  -in deploy.enc -out deploy_key -d; fi
- cd $TRAVIS_BUILD_DIR/scripts
- chmod 755 ghp.sh
- "./ghp.sh"
env:
  global:
  - secure: S0IDi4kPfZ7Dv5u/Q5fRZ9qo//wI1apdzwYXsZDAvqbyFuoYRB0xOkJYgtli+r01JeCtGjqEBnQeRInfcKO9ruL/Lo8KXG6NovQHgAU2yO5fY/u7KAoSU8YCcR7sfXTPU3LbmIQytWuBkKmL7AP7jd4c6+xcvLcEcyWct6Q57KE+B3hlV6XkacFJgR5Ahl1zCXQce6n/YkAikzY1BkwrNmOVObE4qjcWC8DkCzNgFO/QucxRQXNNSBMbXonVdpdSXsUN5Mneve5sQ/RbCLOSYgcg7gsI+YCCz8v0ekmDYXCeMl/ijqE4Qe87otNL+ifL+dLKBNbN0GAN4g82WNBfom90jUvaQ9AopFugTv1uqIse8IDF4euyVsBfRmZzMSlia5DLGc/sY5bJo+revKqi927xGs/TQvXPVb4KY7Er3DCqmFuSBu+KGqSLw2vAhSdqKKh2RrziAzbOhrDD5A5CeEuTH7YfU+bTTVFxMlSP7hALkPHF0rXWE8+kqsiKERbltefZFAUldcE2hMo4VPcTY3kZ1aEjpGvP1/DL9hYBqOQwzA9clacdrfK2qJr77xxwdOcAz6X/htz6YVmuStbWz9gFA9uSyyn2mNnL53jaofDY7M/ixLTUtampdF0+2p6g72FEDXZnukcq2Z2lb+UKBZ0IMbwAALhiyh8GYfzPrKA=
  - secure: i8Dmm/AmhPTOJXw3Q7NoLy4zOW1Q3UC1yoUv+d2V7MRKwGmr3WmHw04wcvsEeKkrPKBvRkLsHd3/g52XjtFSE5s7tPaWAjjOebWdtq7Bwi6rJLh1iZSC0mYsakqz5s9gNt2c+yPJmrnm1EyLnpN5O2bkoBe8qVeVBmNoeqJ+K3Uwm/P1GH/LAYSZ6+8ZJ8DmemsVMkLF0ZpaZwkpAX/phclnRuP2+BR8Qs18T6H6NFw8KiFi+mjuasWqx0J5DYMJGaeAWSuF8op9AImjUFzwjBspQTNRBapWEVIksRtodGPyM2X68GotxDMY5Umu88P9tJufLZTGNxrkD0gjmPOOqdsSaSE1j408QJfTtg6hq71rkdVL9DgGZFgN6NlVxjhT1IvYc3yrIx1LQ9IbHdh5Mur9RWFXOX7zFExb8w1nukhFYYmd12e1RGOIAu8ohGfNZJd7uKJD1ronyvQoKdbQ1EdWYzsvHwVWXpvs+8HdsZ6D70WRMYv4MuBNjQoBY8obw1AelmMGchT/sz7Rbl2TH5n0ncoUeslIOUBgIOzHgIIW7ewfw9X/BQzKYjC95gMWOf+lkVdylZEBvhrWi+BDqO/a8+R6Q5UAS1v2obHMuJSVROx6eEunW2crqVTUGLQQcJAYgqNypXw9UzOkoSsNMVDMgwhg+PSHCi9Gfijc1Ek=
  - secure: lYHRLJhhAw5QHWvLBsX27dyf41TX3CqPJr8RCDsIuUFk+xfw+YmSDHHhM5xP6jiAKubgzEe/8bYKVhrUq5toI4DykggHWAykKf/mo1kxpgtGuAXGFYsGo04x/vzsEt3ZdNsvqneJwi3G82vO6xtFgOddoSluqbL7SQPmh2OJYwSPnMGycHuSLcR2RTBMpVoRzQRVlCK9T+3sSUod3O/ZiQf6ZbnMkyD1WrEr/miZ4QWZufieqq8KfWQsrKNCY1Zrq1X5/8fMzv0Ng099L70Xlvx3JWW8Rp+WEAeknAvzHfnRzR8JobeM77SiOnwB7rM9TlnwVxEyeyz6a1zXCxxgthgSmn4tu4T8WrDUNBMwqs89r/4xFlu+dqmzV4ZPwDgeM8aht/CaiglrcuJcNuDFFEFXq+zgw9eNjtvDpSnWiGq52vHwxXt8K40EJ/bstfMziF8KHsWYXTFMRjfWia08RaT1ZisXER828jdUsclHhiBtl28wk8TJrCTS/M0wnHIYhstJcpBTQtNT6COQvXJO3kR5lqnjWGGJokjlOnDj8nA+ue1OTDPM02vhPIOsCaMt71C2/b4s7bpv8bAk2UDYs5cE2z1nUQ/wnBS/mOrJH9islDWXAcvq/JZRa3RqZkqJyepaH3XZol7v8sPgDjR5/TDvGnB+UxclMYuNHvAk/lI=
  - secure: 03394w1t6nxx2NN++ujMHQzZpLrhqhGAFW4KwoQr3b1Dwft38TkYncB4D6k9YYPoS8D9UsTkYluXPDTu+HUGFbw26MSAV59D73vpXkNtXehNrR53robqDSmLYkv5YihF3Fci+/nXHT7CWh2ehN9vLhf7L85/Z2NiwscGzA5rGLQ0x01YsmeHAVGmwY9qDEOiJCKXRVSCguCTPaSLb8KJV0QKUFXwYOQfsWa/rj/7qEjMm8lo+69KfdDDK0CPU7zi4D7PNGnXFNBpGtwaCKAUrB0HwiFVe16w/cyaWNwm902npaXj7IWsygh3n8kytJqHtnz9PeXLXGChcQxjpXsUbNg/Xy8hjUsYp93x4Sr5RWNpfN8sMhZYXrlhPdwBLiIb1WQZiUD0zz+9aRkvn2kw1ojuAr7doWTLi55abMA7W2xDAF1Sw9qgs4zQOD8l2XD5kAkrFeWKeaEo8jo8nDX0gkOa0pxMPO3vt/9CL8Ss3d4Bgg1SYsjBMoVgKA73o2T66+13c1ESi273Var2Zt4wiCwV0cgoQU+pKHtiJqTJJJ3zBbDkeQhaZh3a6TU/V7UepyJlwJn3TbvZpK5MnPwN8ttb5TwZQIIzIMZ8MOY1suZCnRQsjqUT2+rbbiUUfg2wOeJ51KSYIR5qDoCqiZoC5sw414J77SrgHAbWAT2ugF4=
